spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth
    password: 123456abc
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8071

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



jwt:
  secret: "Jalrz9_Train!2025carHelicopter_13"
  expiration: 900000
  refresh-expiration: 604800000

