spring:
  application:
    name: department-service

  config:
    import: "optional:configserver:http://localhost:8088"

  datasource:
    url: jdbc:postgresql://localhost:5432/department_db
    username: employee
    password: 123456abc
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8091
