server:
  port: 8050

spring:
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  circuitbreaker:
    instances:
      city-service:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instance:
      city-service:
        maxRetryAttempts: 3
        waitDuration: 5s